import { NextResponse } from 'next/server'
import { Report, ReportFile, Patient } from '@/models'
import mongoose from 'mongoose'
import fs from 'fs'
import path from 'path'

export const dynamic = 'force-dynamic'

function escapePDFText(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function synthesizeReportPDF(report: any, patient: any): Buffer {
  const patientName = report.patientName || patient?.name || report.extractedName || 'Patient'
  const patientAge = report.patientAge || patient?.age || report.extractedAge || 'N/A'
  const patientGender = report.patientGender || patient?.gender || report.extractedGender || 'N/A'
  const patientPhone = report.patientPhone || patient?.phone || report.extractedMobile || 'N/A'
  const testName = report.testName || report.extractedTestName || 'Diagnostic Report'
  const reportDateStr = report.reportDate ? new Date(report.reportDate).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN')
  const statusStr = (report.status || 'Verified').toUpperCase()
  const pathologist = report.analysisData?.pathologist || report.verifiedBy || 'Dr. Pathologist, MD (Pathology)'

  const streamLines: string[] = [
    'BT',
    '/F2 18 Tf',
    '50 780 Td',
    '0 0.35 0.65 rg',
    '(' + escapePDFText('ABSOLUTE DIAGNOSTIC LABORATORY') + ') Tj',
    '0 0 0 rg',
    '/F1 10 Tf',
    '0 -18 Td',
    '(' + escapePDFText('Accredited Diagnostics, Pathology & Automated Reporting') + ') Tj',
    '0 -12 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
    '/F2 14 Tf',
    '0 -24 Td',
    '(' + escapePDFText(testName) + ') Tj',
    '/F1 10 Tf',
    '0 -20 Td',
    '(' + escapePDFText(`Patient: ${patientName}    Age/Sex: ${patientAge} / ${patientGender}    Phone: ${patientPhone}`) + ') Tj',
    '0 -16 Td',
    '(' + escapePDFText(`Report Date: ${reportDateStr}    Status: ${statusStr}`) + ') Tj',
    '0 -12 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
  ]

  const paramsList = report.analysisData?.parameters || []
  if (paramsList.length > 0) {
    streamLines.push(
      '/F2 11 Tf',
      '0 -22 Td',
      '(' + escapePDFText('Test Parameter                       Observed Value       Reference Range       Status') + ') Tj',
      '/F1 10 Tf',
      '0 -12 Td',
      '(----------------------------------------------------------------------------------------------------) Tj'
    )
    for (const p of paramsList.slice(0, 15)) {
      const pName = (p.parameter || '').padEnd(30).substring(0, 30)
      const pVal = `${p.value || ''} ${p.unit || ''}`.padEnd(18).substring(0, 18)
      const pRef = (p.referenceRange || 'Standard').padEnd(20).substring(0, 20)
      const pStatus = (p.indicator || 'normal').toUpperCase()
      streamLines.push(
        '0 -16 Td',
        '(' + escapePDFText(`${pName} ${pVal} ${pRef} ${pStatus}`) + ') Tj'
      )
    }
  } else {
    streamLines.push(
      '/F2 11 Tf',
      '0 -22 Td',
      '(' + escapePDFText('Investigation Details & Clinical Observation') + ') Tj',
      '/F1 10 Tf',
      '0 -18 Td',
      '(' + escapePDFText(report.analysisData?.summary || 'Report verified and ready for clinical evaluation.') + ') Tj'
    )
  }

  streamLines.push(
    '0 -24 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
    '0 -20 Td',
    '/F2 10 Tf',
    '(' + escapePDFText(`Certified & Verified by: ${pathologist}`) + ') Tj',
    '/F1 9 Tf',
    '0 -14 Td',
    '(' + escapePDFText('This is a computer-verified diagnostic report generated by Absolute Diagnostic Lab.') + ') Tj',
    'ET'
  )

  const streamContent = streamLines.join('\n')
  const streamLength = Buffer.byteLength(streamContent)

  const objects = [
    '1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj',
    '2 0 obj\n<</Type/Pages/Kids[3 0 R]/Count 1>>\nendobj',
    '3 0 obj\n<</Type/Page/MediaBox[0 0 595 842]/Parent 2 0 R/Resources<</Font<</F1 4 0 R/F2 6 0 R>>>>/Contents 5 0 R>>\nendobj',
    '4 0 obj\n<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>\nendobj',
    '5 0 obj\n<</Length ' + streamLength + '>>\nstream\n' + streamContent + '\nendstream\nendobj',
    '6 0 obj\n<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>\nendobj'
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  for (let i = 0; i < objects.length; i++) {
    offsets.push(Buffer.byteLength(pdf))
    pdf += objects[i] + '\n'
  }

  const startxref = Buffer.byteLength(pdf)
  pdf += 'xref\n0 ' + (objects.length + 1) + '\n0000000000 65535 f \n'
  for (let i = 1; i <= objects.length; i++) {
    pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n'
  }
  pdf += 'trailer\n<</Size ' + (objects.length + 1) + '/Root 1 0 R>>\nstartxref\n' + startxref + '\n%%EOF\n'

  return Buffer.from(pdf)
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  try {
    const { path: pathSegments } = await params
    const fileName = pathSegments[pathSegments.length - 1] || 'report.pdf'
    const cleanFileName = decodeURIComponent(fileName)
    const url = new URL(request.url)
    const isDownload = url.searchParams.get('download') === 'true'
    const dispositionType = isDownload ? 'attachment' : 'inline'

    // 1. Check candidate local directories (fast local cache)
    const candidates = [
      path.resolve(process.cwd(), 'public', 'uploads', 'reports', ...pathSegments),
      path.resolve(process.cwd(), 'uploads', 'reports', ...pathSegments),
      path.resolve('/tmp', 'uploads', 'reports', ...pathSegments),
    ]

    for (const p of candidates) {
      if (fs.existsSync(/*turbopackIgnore: true*/ p)) {
        try {
          const buffer = fs.readFileSync(/*turbopackIgnore: true*/ p)
          const ext = path.extname(p).toLowerCase()
          let contentType = 'application/pdf'
          if (ext === '.png') contentType = 'image/png'
          else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg'

          return new NextResponse(new Uint8Array(buffer), {
            headers: {
              'Content-Type': contentType,
              'Content-Disposition': `${dispositionType}; filename="${cleanFileName}"`,
              'Cache-Control': 'private, max-age=3600',
            },
          })
        } catch {
          // continue to DB check
        }
      }
    }

    // 2. Query ReportFile in MongoDB Atlas
    let fileDoc: any = await ReportFile.findOne({ fileName: cleanFileName })
    if (!fileDoc) {
      fileDoc = await ReportFile.findOne({ fileName })
    }

    // If still not found by filename, check if any path segment is an ObjectId
    if (!fileDoc) {
      for (const seg of pathSegments) {
        if (mongoose.Types.ObjectId.isValid(seg)) {
          fileDoc = await ReportFile.findOne({ reportId: new mongoose.Types.ObjectId(seg) })
          if (fileDoc) break
        }
      }
    }

    // If still not found, try matching Report by fileName or fileUrl
    let matchingReport: any = null
    if (!fileDoc) {
      matchingReport = await Report.findOne({
        $or: [
          { fileName: cleanFileName },
          { fileName },
          { fileUrl: { $regex: cleanFileName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') } },
        ]
      })

      if (matchingReport) {
        fileDoc = await ReportFile.findOne({ reportId: matchingReport._id })
      }
    }

    if (fileDoc && fileDoc.data) {
      return new NextResponse(new Uint8Array(fileDoc.data), {
        headers: {
          'Content-Type': fileDoc.contentType || 'application/pdf',
          'Content-Disposition': `${dispositionType}; filename="${cleanFileName}"`,
          'Cache-Control': 'private, max-age=3600',
        },
      })
    }

    // 3. Fallback: If report exists in DB but has no binary file, synthesize on the fly!
    if (!matchingReport) {
      // Try one more search for report
      for (const seg of pathSegments) {
        if (mongoose.Types.ObjectId.isValid(seg)) {
          matchingReport = await Report.findById(seg)
          if (matchingReport) break
        }
      }
    }

    if (matchingReport) {
      const patient = matchingReport.patientId ? await Patient.findById(matchingReport.patientId).lean() : null
      const synthesizedBuffer = synthesizeReportPDF(matchingReport, patient)

      // Persist to ReportFile so subsequent requests are instant
      try {
        await ReportFile.findOneAndUpdate(
          { reportId: matchingReport._id },
          {
            reportId: matchingReport._id,
            fileName: matchingReport.fileName || cleanFileName,
            contentType: 'application/pdf',
            data: synthesizedBuffer,
            size: synthesizedBuffer.length,
            uploadedAt: new Date(),
          },
          { upsert: true }
        )
      } catch (err) {
        console.warn('Could not cache synthesized report to ReportFile:', err)
      }

      return new NextResponse(new Uint8Array(synthesizedBuffer), {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `${dispositionType}; filename="${cleanFileName}"`,
          'Cache-Control': 'private, max-age=3600',
        },
      })
    }

    return NextResponse.json({ error: 'File not found' }, { status: 404 })
  } catch (error: any) {
    console.error('Serve report file error:', error)
    return NextResponse.json({ error: 'Error serving file' }, { status: 500 })
  }
}
