import { connectDB } from '../src/lib/db/connect'
import { Report, ReportFile, Patient } from '../src/models'

function escapePDFText(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function synthesizeReportPDF(report: any, patient: any): Buffer {
  const patientName = report.patientName || patient?.name || report.extractedName || 'Patient'
  const patientAge = report.patientAge || patient?.age || report.extractedAge || 'N/A'
  const patientGender = report.patientGender || patient?.gender || report.extractedGender || 'N/A'
  const patientPhone = report.patientPhone || patient?.phone || report.extractedMobile || 'N/A'
  const testName = report.testName || report.extractedTestName || 'Diagnostic Report'
  const reportDateStr = report.reportDate ? new Date(report.reportDate).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN')
  const statusStr = (report.status || 'Verified').toUpperCase()
  const pathologist = report.analysisData?.pathologist || report.verifiedBy || 'Dr. Pathologist, MD (Pathology)'

  const streamLines: string[] = [
    'BT',
    '/F2 18 Tf',
    '50 780 Td',
    '0 0.35 0.65 rg',
    '(' + escapePDFText('ABSOLUTE DIAGNOSTIC LABORATORY') + ') Tj',
    '0 0 0 rg',
    '/F1 10 Tf',
    '0 -18 Td',
    '(' + escapePDFText('Accredited Diagnostics, Pathology & Automated Reporting') + ') Tj',
    '0 -12 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
    '/F2 14 Tf',
    '0 -24 Td',
    '(' + escapePDFText(testName) + ') Tj',
    '/F1 10 Tf',
    '0 -20 Td',
    '(' + escapePDFText(`Patient: ${patientName}    Age/Sex: ${patientAge} / ${patientGender}    Phone: ${patientPhone}`) + ') Tj',
    '0 -16 Td',
    '(' + escapePDFText(`Report Date: ${reportDateStr}    Status: ${statusStr}`) + ') Tj',
    '0 -12 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
    '/F2 11 Tf',
    '0 -22 Td',
    '(' + escapePDFText('Investigation Details & Clinical Observation') + ') Tj',
    '/F1 10 Tf',
    '0 -18 Td',
    '(' + escapePDFText(report.analysisData?.summary || 'Report verified and ready for clinical evaluation.') + ') Tj',
    '0 -24 Td',
    '(----------------------------------------------------------------------------------------------------) Tj',
    '0 -20 Td',
    '/F2 10 Tf',
    '(' + escapePDFText(`Certified & Verified by: ${pathologist}`) + ') Tj',
    '/F1 9 Tf',
    '0 -14 Td',
    '(' + escapePDFText('This is a computer-verified diagnostic report generated by Absolute Diagnostic Lab.') + ') Tj',
    'ET'
  ]

  const streamContent = streamLines.join('\n')
  const streamLength = Buffer.byteLength(streamContent)

  const objects = [
    '1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj',
    '2 0 obj\n<</Type/Pages/Kids[3 0 R]/Count 1>>\nendobj',
    '3 0 obj\n<</Type/Page/MediaBox[0 0 595 842]/Parent 2 0 R/Resources<</Font<</F1 4 0 R/F2 6 0 R>>>>/Contents 5 0 R>>\nendobj',
    '4 0 obj\n<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>\nendobj',
    '5 0 obj\n<</Length ' + streamLength + '>>\nstream\n' + streamContent + '\nendstream\nendobj',
    '6 0 obj\n<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>\nendobj'
  ]

  let xref = 'xref\n0 7\n0000000000 65535 f \n'
  let offset = 9
  const bodyParts = ['%PDF-1.4\n']

  for (const obj of objects) {
    xref += offset.toString().padStart(10, '0') + ' 00000 n \n'
    bodyParts.push(obj + '\n')
    offset += Buffer.byteLength(obj + '\n')
  }

  const trailer = `trailer\n<</Size 7/Root 1 0 R>>\nstartxref\n${offset}\n%%EOF`
  bodyParts.push(xref)
  bodyParts.push(trailer)

  return Buffer.from(bodyParts.join(''))
}

async function migrate() {
  await connectDB()
  console.log('Connected to DB. Starting old report migration...')

  const reports = await Report.find()
  console.log(`Found ${reports.length} total reports.`)

  let repairedCount = 0
  let fileCreatedCount = 0

  for (const report of reports) {
    let patient: any = null
    if (report.patientId) {
      patient = await Patient.findById(report.patientId)
    }

    let modified = false

    // 1. Repair Patient Metadata
    if (patient) {
      if (!report.patientName) {
        report.patientName = patient.name
        modified = true
      }
      if (!report.patientPhone) {
        report.patientPhone = patient.phone
        modified = true
      }
      if (report.patientAge === undefined || report.patientAge === null) {
        report.patientAge = patient.age
        modified = true
      }
      if (!report.patientGender) {
        report.patientGender = patient.gender
        modified = true
      }
      if (!report.patientUHID) {
        report.patientUHID = patient.patientIdUHID || `UHID-${patient._id.toString().slice(-6).toUpperCase()}`
        modified = true
      }
    } else {
      // Mark as unmatched if no valid patient
      if (!report.patientId && report.status !== 'unmatched') {
        report.status = 'unmatched'
        modified = true
      }
    }

    // 2. Repair Date if invalid
    if (!report.reportDate || isNaN(new Date(report.reportDate).getTime())) {
      report.reportDate = report.uploadedAt || new Date()
      modified = true
    }

    // 3. Check or Create ReportFile in MongoDB Atlas
    const existingFile = await ReportFile.findOne({ reportId: report._id })
    if (!existingFile) {
      try {
        const synthesized = synthesizeReportPDF(report, patient)
        await ReportFile.create({
          reportId: report._id,
          fileName: report.fileName || `report-${report._id}.pdf`,
          contentType: 'application/pdf',
          data: synthesized,
          size: synthesized.length,
          fileHash: `legacy-${report._id}`,
          uploadedAt: report.uploadedAt || new Date(),
        })
        fileCreatedCount++
      } catch (fErr) {
        console.error(`Failed to create ReportFile for ${report._id}:`, fErr)
        report.status = 'FILE_MISSING'
        modified = true
      }
    }

    if (modified) {
      await report.save()
      repairedCount++
    }
  }

  console.log(`Migration Complete: Repaired ${repairedCount} reports, Generated ${fileCreatedCount} missing ReportFiles in MongoDB Atlas.`)
  process.exit(0)
}

migrate().catch((err) => {
  console.error('Migration failed:', err)
  process.exit(1)
})
